-- Initial schema for courts.ie hybrid app
-- Users authenticate via Google/Azure, approval tracked in app_metadata

-- Comments table: references cases by natural keys
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_source_url TEXT NOT NULL,
    case_number TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for efficient comment lookups by case
CREATE INDEX comments_case_idx ON comments (list_source_url, case_number);
CREATE INDEX comments_user_idx ON comments (user_id);

-- Case status table: tracks done status by natural keys
CREATE TABLE case_status (
    list_source_url TEXT NOT NULL,
    case_number TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    updated_by UUID REFERENCES auth.users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (list_source_url, case_number)
);

-- Helper function to check if user is approved
CREATE OR REPLACE FUNCTION is_approved()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN (
        SELECT COALESCE(
            (auth.jwt() -> 'app_metadata' ->> 'approved')::boolean,
            false
        )
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enable RLS
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_status ENABLE ROW LEVEL SECURITY;

-- Comments policies: only approved users can read/write
CREATE POLICY "Approved users can read comments"
    ON comments FOR SELECT
    USING (is_approved());

CREATE POLICY "Approved users can insert comments"
    ON comments FOR INSERT
    WITH CHECK (is_approved() AND auth.uid() = user_id);

CREATE POLICY "Users can delete own comments"
    ON comments FOR DELETE
    USING (is_approved() AND auth.uid() = user_id);

-- Case status policies: only approved users can read/write
CREATE POLICY "Approved users can read case status"
    ON case_status FOR SELECT
    USING (is_approved());

CREATE POLICY "Approved users can insert case status"
    ON case_status FOR INSERT
    WITH CHECK (is_approved());

CREATE POLICY "Approved users can update case status"
    ON case_status FOR UPDATE
    USING (is_approved());

-- Enable realtime for both tables
ALTER PUBLICATION supabase_realtime ADD TABLE comments;
ALTER PUBLICATION supabase_realtime ADD TABLE case_status;
